FileVersion = 1

[Project]
Name = "BJSON"
TargetType = "BeefLib"
StartupObject = "BJSON.Program"

[[ProjectFolder.Items]]
Type = "AutoFolder"
Name = "Models"

[[ProjectFolder.Items.Items]]
Type = "IgnoreSource"
Name = "JsonValueOld.bf"
